{% set name = "pygame" %}
{% set version = "2.1.2" %}
{% set sha256 = "d6d0eca28f886f0477cd0721ac688189155a587f2bb8eae740e52ca56c3ad23c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0 

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - numpy >=1.16
    - pip
    - python
    - pysdl2
    - sdl2
    - sdl2_image
    - sdl2_mixer
    - sdl2_ttf
    - sdl2_gfx
    - sdl2_net
    - setuptools
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - pysdl2
    - sdl2
    - sdl2_image
    - sdl2_mixer
    - sdl2_ttf
    - sdl2_gfx
    - sdl2_net

test:
  imports:
    - pygame

about:
  home: https://www.pygame.org/news
  dev_url: https://github.com/pygame/pygame
  license: LGPL
  summary: Pygame is a set of Python modules designed for writing video games.
